name: bullseye
description: 'FLutter project'

dependencies:
  flutter:
    sdk: flutter

dev dependencies:
    flutter test:
      sdk: flutter 

environment:
  sdk: '>=2.10.0 <3.0.0'

flutter:
  uses-material-design : true
  assets: 
  - images/
